sudo: true
dist: trusty

env:
  global:
    - REPOSITORY=nginx-node-image

jobs:
  include:
    - stage: Build Image
      script:
      - docker pull parpe/$REPOSITORY:$TRAVIS_BRANCH
      - docker build -t $REPOSITORY:$TRAVIS_BRANCH .
      - docker images
    - stage: Deploy Image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag parpe/$REPOSITORY:$TRAVIS_BRANCH parpe/$REPOSITORY
      - docker push parpe/$REPOSITORY:$TRAVIS_BRANCH